# vim:ft=kitty

## name:     Catppuccin Kitty Macchiato
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/macchiato.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #cad3f5
background              #24273a
selection_foreground    #cad3f5
selection_background    #f4dbd6

# Cursor colors
cursor                  #f4dbd6
cursor_text_color       #24273a

# URL underline color when hovering with mouse
url_color               #f4dbd6

# Kitty window border colors
active_border_color     #b7bdf8
inactive_border_color   #6e738d
bell_border_color       #eed49f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #181926
active_tab_background   #c6a0f6
inactive_tab_foreground #cad3f5
inactive_tab_background #1e2030
tab_bar_background      #181926

# Colors for marks (marked text in the terminal)
mark1_foreground #c6a0f6
mark1_background #b7bdf8
mark2_foreground #c6a0f6
mark2_background #b7bdf8
mark3_foreground #c6a0f6
mark3_background #7dc4e4

# The 16 terminal colors

# black
color6 #8b5162
color14 #4b5162

# red
color3 #710000
color11 #9A1119

# green
color2  #1ac5b0
color10 #9ac5b0

# yellow
color1  #fdf500
color9 #fdf691

# blue
color4  #37ebf3
color12 #37ebf3

# magenta
color5  #9370db
color13 #9370db

# cyan
color0  #cb1dcd
color8 #cb1dcd

# white
color7  #d1c5c0
color15 #d1c5c0
