shell = "zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
hooks.add = """
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
"""
