---
- name: Install tmux (macOS)
  community.general.homebrew:
    name: tmux
    state: present
  when: ansible_os_family == "Darwin"

- name: Install tmux (Debian)
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install tmux (RedHat)
  ansible.builtin.dnf:
    name: tmux
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Clone TPM
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    depth: 1

- name: Install tmux plugins via TPM
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins
  args:
    creates: "{{ ansible_env.HOME }}/.tmux/plugins/catppuccin"
